### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by robfuscator** [bjoluc/jspsych-builder#10]
Hey!

I'm programming a jsPsych study with your tool and just tried to make the shift to TypeScript, as it could add some robustness to my code. Now, as far as I can tell, `jspsych-builder` does not yet support TypeScript (if I specify `experiment.ts` as my experiment-file, I get an error stating the `Experiment file ./src/experiment.ts.js does not exist.`).

Since you are using Webpack and Babel internally already, I think it would be not that much effort to add TypeScript support. Have you thought about including that functionality? Would be awesome :).

Kind regards,
r

**Comment by Haffi921** [comment]
Can we get this? I would really like to write typescript.

Perhaps some sort of a typescript option at `init` given an option `--typescript`? Or perhaps that we can dynamically detect if typescript files are present and continue on from there?

**Comment by bjoluc** [comment]
Hi both,
> Since you are using Webpack and Babel internally already, I think it would be not that much effort to add TypeScript support. Have you thought about including that functionality?

absolutely! It's been on my agenda for a while, but now that you two ask, I'm happy to prioritize this!

> Perhaps some sort of a typescript option at init given an option --typescript? Or perhaps that we can dynamically detect if typescript files are present and continue on from there?

I like the `--typescript` init flag. To get this going quickly though, I think it is sufficient for now to just support compilation of `.ts` files (via ts-loader). For the `experiment-file` argument, I think we can keep omitting the file suffix, but look for `.ts` *and* `.js` files under the hood and prefer `.ts` if it is available. Oh, and maybe we should support the full filename as well...

Anyway, I'm hoping to work on this next week!

**Comment by Haffi921** [comment]
Great! I think just `.ts` compilation support in general is the main and most important thing. A `--typescript` flag would (I imagine) just generate an `experiment.ts` instead of `experiment.js`, which is nice but not crucial since people can always just change the extension to `.ts` themselves.

Looking forward to this feature!
