### ISSUE TITLE
Can't disable displayData

### ISSUE THREAD

**Issue by shirdekel** [bjoluc/jspsych-builder#15]
I see that `app.js` calls `jsPsych.data.displayData()` by default, but I'm struggling to disable it for both development and packaged versions.

For instance, specifying an empty function for `on_finish` doesn't help:

```js
  const jsPsych = initJsPsych({
    on_finish: function() {
    }
  });
```

**Comment by shirdekel** [comment]
Seems I worked it out. Just need to comment out the call to return the jsPsych instance:
```js
// return jsPsych;
```

**Comment by bjoluc** [comment]
Hi @shirdekel,
[this](https://github.com/bjoluc/jspsych-builder#experiment-files) is the corresponding section in the readme, but I'm not sure if it's clear enough. Any suggestions are most welcome!

**Comment by shirdekel** [comment]
Thanks. Is the implication in that section that commenting out the `jsPsych` call is the recommended way to not display the results in the browser? If so, I'd say making this explicit would be clearer 😃

**Comment by bjoluc** [comment]
Right, I hope it's clearer now. Thanks!

**Comment by shirdekel** [comment]
Looks good 👍
