### ISSUE TITLE
Possibility to supply 'endPage.html' for JATOS

### ISSUE THREAD

**Issue by robfuscator** [bjoluc/jspsych-builder#18]
`jspsych-builder` allows for packaging the experiment to run on a JATOS server, and that's a great thing. When an experiment run with JATOS ends, a basic _end of study_ message is displayed, but JATOS allows for customizing this by supplying an `endPage.html` file. I think it would be very convenient, if one could supply such a file to `jspsych-builder` to have it added to the built JATOS packages.

I tried using the `@miscDir` pragma, but it does not seem to work for me.

What do you think of this?

**Comment by bjoluc** [comment]
Good point. I think the reason that `@miscDir` doesn't work here is that it only accepts directories and replicates the provided path in the study assets directory. We would need a way to specify files here as well, so you could have `@miscDir endPage.html`, which would still be pretty confusing due to the "dir". I don't particularly like the "Dir" pragma names anyway and think they should also support files. We can only rename them in the next major release though, so it may be best to keep the names for now and start supporting file paths in a minor release. WDYT?

**Comment by robfuscator** [comment]
Sounds like a good solution to me.

Is it allowed to specify the same pragma multiple times? Otherwise only those who didn't use the `@miscDir` pragma already would benefit from the new feature.

Another option I can think of would be the introduction of a general `@asset` pragma to include files of any kind on the root level of the assets directory. But I'm not sure if this would bring any benefit over the existing _audio-images-video-misc_-structure.

**Comment by bjoluc** [comment]
> Is it allowed to specify the same pragma multiple times? Otherwise only those who didn't use the @miscDir pragma already would benefit from the new feature.

Nope, but comma-separated lists of paths are allowed :) Again, the "Dir" is pretty confusing here... Should rather be "Dirs" right now.

> Another option I can think of would be the introduction of a general @asset pragma to include files of any kind on the root level of the assets directory. But I'm not sure if this would bring any benefit over the existing audio-images-video-misc-structure.

What about supporting files and paths in all pragmas and renaming `@miscDir` to `@assets` in the long term, along with `@audioAssets`, ..., or the like (naming is hard)? I don't really see the need for another pragma then.

**Comment by robfuscator** [comment]
> Nope, but comma-separated lists of paths are allowed :)

Wonderful!

> What about supporting files and paths in all pragmas and renaming `@miscDir` to `@assets` in the long term, along with `@audioAssets`, ..., or the like (naming is hard)? I don't really see the need for another pragma then.

Yes, I like that idea. I think it's more clear than _misc_ and _Dir_. Also, this would leave users with the option to use your predefined assets structure, but also enable them to create their own structure from scratch using just `@assets`. (I guess with the current solution this is already possible for asset directories, but not very intuitive.)

**Comment by bjoluc** [comment]
Even better maybe: Deprecating all "Dir" pragmas and introducing only `@assets` which resolves all dir/file paths from the root directory and detects media types on a per-file basis! You're absolutely right that the current solution is not very intuitive.

**Comment by robfuscator** [comment]
Sounds very streamlined and convenient to me. Looking forward to this :rocket:.
