### ISSUE TITLE
npx?

### ISSUE THREAD

**Issue by kalaschnik** [bjoluc/jspsych-builder#24]
I am first-time jsPsych user. Love the project!

Since you provided a `bin` entry in `package.json`, I could successfully set up my environment with:
`npx jspsych-builder init`, which has generally a lot of benefits compared to `npm -g ...`. Yet, as this is my first day reading about the setup, maybe I miss the reason to not do that?

Otherwise, I would actually promote that method also in your README.md.

**Comment by bjoluc** [comment]
> maybe I miss the reason to not do that?

I don't think there is one, especially since `jspsych-builder` is included in the dependencies of the project that `init` creates. Only that the `jspsych` command and its CLI completion are not directly available then. Maybe the readme should offer both options. WDYT? Would you like to craft a PR?

**Comment by kalaschnik** [comment]
I can do that, and also briefly outline some advantages.
