### ISSUE TITLE
Correct way to put preload plugin in its own file

### ISSUE THREAD

**Issue by kalaschnik** [bjoluc/jspsych-builder#31]
How would I refactor the Preload Plugin, so I can use it from an external file?

Right now I am having a file in `./components/preload.js` which looks like this:

```javascript
import PreloadPlugin from '@jspsych/plugin-preload';

const assetPaths = 'assets/'; // <- this must be wrong

export const preload = {
  type: PreloadPlugin,
  images: assetPaths.images,
  audio: assetPaths.audio,
  video: assetPaths.video,
};

```

my `experiment.js`

```javascript
/**
 * @title Demo
 * @description
 * @version 0.1.0
 */
import '../styles/main.scss';

import { preload } from './components/preload';
import { welcome } from './components/welcome';
import { fullscreen } from './components/fullscreen';
// etc.
```

This fails because the `run` function cannot find `assetPaths`. I tried putting `assetPath` in my export object and reference to it, but that also failed... 

```javascript
export async function run({
  assetPaths,
  input = {},
  environment,
  title,
  version,
})
```
any ideas how to solves? I guess this is more a JS is issue that I create, instead of jsPsychBuilder issue; yet, I would love to keep my `experiment.js` as minimal as possible

**Comment by bjoluc** [comment]
Your'e on a good track already – all you need to do is pass `assetPaths` from the `run` function to a function in `./components/preload.js`:

```diff
import PreloadPlugin from '@jspsych/plugin-preload';

- const assetPaths = 'assets/'; // <- this must be wrong

- export const preload = {
+ export const getPreloadTrial = (assetPaths) => ({
  type: PreloadPlugin,
  images: assetPaths.images,
  audio: assetPaths.audio,
  video: assetPaths.video,
});
```

Then, in the `run` function, you can push the return value of `getPreloadTrial(assetPaths)` to your timeline.
