### ISSUE TITLE
Troubles uploading data to jatos

### ISSUE THREAD

**Issue by franfrutos** [bjoluc/jspsych-builder#38]
I'm a bit new to jsPsych and web development in general and I may ask a trivial question, but is it possible to use the jatos library inside the experiment file?

The documentation seems to indicate that the only option is to use return at the end of the function containing the experiment to connect with jatos server, but it would be nice to know if it is possible to load the jatos library to handle session related issues by "hand".

**Comment by franfrutos** [comment]
I have just discovered that the jatos library can be accessed if the studio is running on the jatos server.

**Comment by wdhub** [comment]
> I have just discovered that the jatos library can be accessed if the studio is running on the jatos server.

That's nice! how did you access the jatos library in the code exactly?

**Comment by bjoluc** [comment]
Simply `jatos` should do – it's a global variable in any experiment run by JATOS :slightly_smiling_face:

**Comment by franfrutos** [comment]
> > I have just discovered that the jatos library can be accessed if the studio is running on the jatos server.
> 
> 
> 
> That's nice! how did you access the jatos library in the code exactly?

Hey! Sorry for the delayed response. [here](https://github.com/franfrutos/CPT3_PyA/blob/main/src/experiment.js) you can find a repo were I access the JATOS library.
