### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by AtomicNess123** [bjoluc/jspsych-builder#44]
How to install this tool? I'm on a MAC and would like to know how to get started for a nonprogrammer. Thanks!

**Comment by bjoluc** [comment]
Hi @AtomicNess123,
you'll have to [install Node.js](https://nodejs.org/en/download/) first and know how to open a terminal. Then following the [Getting started section](https://github.com/bjoluc/jspsych-builder#getting-started) should be all you need to do. I recommend [Visual Studio Code](https://code.visualstudio.com/) for editing the script files later on. Let me know if there's anything unclear. Cheers!

**Comment by AtomicNess123** [comment]
Thanks!

**Comment by AtomicNess123** [comment]
I got this error:

```
jsPsych-builder is ready to initialize your experiment. Continue? Yes
  ✔ Compiling project template
  ✖ Installing dependencies
    → spawn npm EAGAIN

Error:
Command failed with EAGAIN: npm install
spawn npm EAGAIN
```

**Comment by bjoluc** [comment]
Well, that's odd. `jspsych-builder` is trying to run `npm install` in the newly created directory, which somehow fails. Would you mind opening the new directory in a terminal and running `npm install` yourself to see what it logs to the console?

**Comment by AtomicNess123** [comment]
All good now, for some reason :)

**Comment by bjoluc** [comment]
Interesting. Let's hope it was just a network connection problem or the like :see_no_evil:
