### ISSUE TITLE
Does jsPsych Builder support React?

### ISSUE THREAD

**Issue by fenglier** [bjoluc/jspsych-builder#48]
Hello, does jsPsych Builder support React? I haven't seen any examples indicating that React can be used.

**Comment by bjoluc** [comment]
Hi @fenglier,
jsPsych Builder does support React/JSX – just rename the relevant source file(s) to `.jsx`/`.tsx` and you should be good to go. I'm aware of the lack of examples (#20), so I'm closing this as a duplicate of #20.
Cheers!

**Comment by fenglier** [comment]
thanks
