### ISSUE TITLE
Can I add a proxy to devServer?

### ISSUE THREAD

**Issue by fenglier** [bjoluc/jspsych-builder#49]
Every time I need to debug with the backend, I have to package the code and deploy it to the server where the backend is located. This process is quite cumbersome. Therefore, can I set up a proxy for the development server to save a lot of time?

**Comment by fenglier** [comment]
I found that the configuration for devServer is located in tasks.ts, but I don't have control over it.
![image](https://github.com/bjoluc/jspsych-builder/assets/30134217/8f204129-2005-4eb5-8fa8-0605ad63a716)

**Comment by bjoluc** [comment]
Hey @fenglier,
you're absolutely right that there should be a way to alter the devServer config. I'm thinking about supporting this in `builder.config.mjs`, but it will probably be a week or so until I have a decent block of time to look into it. I'll update you here once I get to it.
Cheers!

**Comment by fenglier** [comment]
> Hey @fenglier, you're absolutely right that there should be a way to alter the devServer config. I'm thinking about supporting this in `builder.config.mjs`, but it will probably be a week or so until I have a decent block of time to look into it. I'll update you here once I get to it. Cheers!

oo, thanks
