### ISSUE TITLE
app.js.LICENSE.txt

### ISSUE THREAD

**Issue by robfuscator** [bjoluc/jspsych-builder#9]
Hey!

First of all, thanks, your project is awesome.

I'm actually not sure if this is an issue or not, but I just discovered a file called `app.js.LICENSE.txt` next to the `app.js` bundle, which says that the "Microsoft Corporation" has a copyright on the bundle. Is this the expected behavior?

This is the content:

```
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
```

Regards,
r

**Comment by bjoluc** [comment]
Hi @robfuscator,

thanks for the kind words! The copyright notice is part of the jsPsych bundle and [seems to pertain to tslib](https://stackoverflow.com/questions/52849894/how-to-handle-copyright-notice-in-javascript-bundle). Webpack – and hence jspsych-builder – retains the copyright notices in `app.js.LICENSE.txt`. If you're in doubt someone might mistake your app for being licensed by Microsoft, you may consider adding your own license notice to your experiment file s.t. it appears in `app.js.LICENSE.txt` as well.

Cheers!

**Comment by SHogenboom** [comment]
@bjoluc 
Sorry to ‘open’ this issue again! I came here because I also questioned why the license mentioned a company (Facebook in this case).

Unfortunately I don’t understand the solutions provided in the linked StackOverflow or your own comment. Probably because I don’t fully understand the whole npm workflow yet. I mean that is exactly why I was happy to find that `jspsych-builder` worked on the first try! Any additional tips for noobs on how to resolve this license issue? Like how would one go about 
> ..adding your own license notice to your experiment file

Thanks in advance!

**Comment by bjoluc** [comment]
Hi @SHogenboom,

a license comment may look like this:
```ts
/**
 * @title My Experiment
 * [...]
 */
/*! License text goes here */
```
If you'd like to dig deeper, feel free to read up on [webpack](https://webpack.js.org/), the primary tool behind `jspsych-builder`.

> I mean that is exactly why I was happy to find that jspsych-builder worked on the first try!

Well, I'm happy to read that :smile:
